### ISSUE TITLE
Issues with the spellcheck GHA?

### ISSUE THREAD

**Issue by jonasbn** [rh-mobb/documentation#199]
Hello, 

As the maintainer of the [spellcheck GitHub action](https://github.com/marketplace/actions/github-spellcheck-action) I was searching of users of version 0.16.0 of the Spellcheck GHA, as part of my [sunset policy](https://github.com/rojopolis/spellcheck-github-actions/wiki#sunset-policy). I can see that you are referencing it in your code, but the code is commented out.

Do you need assistance or a PR to get it to work, if so please let me know and I will do my best to help and you to assist you.

**Comment by michaelryanmcneill** [comment]
Issue has gone stale, closing.
