### ISSUE TITLE
Azure Key Vault issues?

### ISSUE THREAD

**Issue by patrickstrick** [rh-mobb/documentation#213]
I recently came across a conversation about Azure Key Vault that pointed to this [Red Hat Knowledge Article](https://access.redhat.com/solutions/6522771) stating that it is not supported and can (will?) cause issues when the cluster is upgraded.

Can the MOBB team reconcile that article with the instructions you have documented [here](https://github.com/rh-mobb/documentation/blob/main/docs/security/secrets-store-csi/azure-key-vault.md)? Either it will break upgrades and we should not tell people to install it, or it no longer has that problem and the Knowledge article should be removed. Thank you.

**Comment by michaelryanmcneill** [comment]
Issue has gone stale, closing.
