### ISSUE TITLE
update docs/aro/add-infra-nodes/ with latest information from Azure docs

### ISSUE THREAD

**Issue by paulczar** [rh-mobb/documentation#373]
since https://mobb.ninja/docs/aro/add-infra-nodes/ was written, Azure started offering (like this last weekend) zero cost OCP subscription for infra nodes.  we should update the doc to include that information, as well as updating the helm chart it uses to ensure we follow the guidelines to get the free subs.

here's the freshly minted Azure doc...  note it mentions specific instance types, node labels, and workloads.

https://learn.microsoft.com/en-us/azure/openshift/howto-infrastructure-nodes#qualified-workloads

**Comment by supernovae** [comment]
I'll run thought this 👍

**Comment by michaelryanmcneill** [comment]
Completed with #567
