### ISSUE TITLE
No need to modify the DNS nameserver from OS when you configure VPN Client

### ISSUE THREAD

**Issue by antmaro** [rh-mobb/documentation#415]
In the following documentation https://mobb.ninja/docs/rosa/vpn/ in the section **Configure your OpenVPN Client** there is a step regarding to add DNS entry for the AWS Resolver 10.x.x.2 in the OS.  There is an option when you create the AWS VPN Client endpoint where you can set up the DNS server that will be use for the Client VPN:

![image](https://github.com/rh-mobb/documentation/assets/8375059/e5b47e66-7e70-40e0-a7e1-e7b2fea694ce)

You can set up the option also via AWS CLI with the option `aws create-client-vpn-endpoint --dns-servers <value>` .

With the previous option, you don't need to add the DNS nameserver, so you can avoid the Note from the documentation.

**Comment by michaelryanmcneill** [comment]
Issue has gone stale, closing.
