### ISSUE TITLE
ROSA - AWS Load Balancer Operator - Non STS Cluster 

### ISSUE THREAD

**Issue by nfrankish** [rh-mobb/documentation#479]
Hi,
The documentation only provides details for a STS cluster - https://github.com/rh-mobb/documentation/blob/main/content/rosa/aws-load-balancer-operator/index.md

Is there documentation available for a Non STS cluster to create the required secrets?

[https://github.com/openshift/aws-load-balancer-operator/issues/121](url)

**Comment by daxelrod-rh** [comment]
Hi, @nfrankish! I have not been able to find any existing documentation that covers how to use the AWS Load Balancer Operator on a Non-STS ROSA cluster. I am following up with relevant teams to see what more information I can find.

**Comment by michaelryanmcneill** [comment]
Issue has gone stale, closing.
