### ISSUE TITLE
Motivations there to have 3 ingress controller replicas instead of the default 2??

### ISSUE THREAD

**Issue by krishvoor** [rh-mobb/documentation#500]
OCP/ROSA docs have default controller replicas of 2 replicas 
https://docs.openshift.com/container-platform/4.13/networking/ingress-operator.html#nw-ingress-controller-configuration-parameters_configuring-ingress 
what's the motivation behind having 3 replicas in ARO?

**Comment by michaelryanmcneill** [comment]
Issue has gone stale, closing.
