### ISSUE TITLE
Azure ARC integration document needs to be updated.

### ISSUE THREAD

**Issue by porrascarlos802018** [rh-mobb/documentation#526]
in this document
https://cloud.redhat.com/experts/aro/azure-arc-integration/
Enable log aggregation instructions needs to be replaced by the ones seen here:

https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-enable?tabs=cli#enable-container-insights

"

Arc-enabled cluster with ARO or OpenShift or Windows nodes

Managed identity authentication is not supported for Arc-enabled Kubernetes clusters with ARO (Azure Red Hat OpenShift) or OpenShift or Windows nodes. Use legacy authentication by specifying amalogs.useAADAuth=false as in the following example.

Azure CLI

Copy
az k8s-extension create --name azuremonitor-containers --cluster-name <cluster-name> --resource-group <resource-group> --cluster-type connectedClusters --extension-type Microsoft.AzureMonitor.Containers --configuration-settings amalogs.useAADAuth=false

**Comment by daxelrod-rh** [comment]
Thank you. We've merged an initial PR #528 to immediately remove the incorrect "Enable log aggregation" section to prevent it from misleading anyone.

We will next work on a corrected version.

**Comment by daxelrod-rh** [comment]
@porrascarlos802018 I think my second round of revisions in #581 should completely address all of your feedback. That said, please let me know if anything else is unclear about these docs.

Thank you again for reporting this!
