### ISSUE TITLE
azure arc workaround doc needs to be modified

### ISSUE THREAD

**Issue by porrascarlos802018** [rh-mobb/documentation#527]
the document https://access.redhat.com/solutions/7064794 

needs to be redirecting customers to 
https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-enable?tabs=cli#enable-container-insights

az k8s-extension create --name azuremonitor-containers --cluster-name <cluster-name> --resource-group <resource-group> --cluster-type connectedClusters --extension-type Microsoft.AzureMonitor.Containers --configuration-settings amalogs.useAADAuth=false

I wouldnt do machine configuration changes

**Comment by daxelrod-rh** [comment]
Hello! The above Red Hat KCS article is not within the scope of this repo; however, I will get your feedback to the author of that article.

My understanding is that the the azuremonitor-metrics extension is for metrics, and serves a different purpose than the azuremonitor-containers extension. The latter is for logs, right?

**Comment by daxelrod-rh** [comment]
The author of https://access.redhat.com/solutions/7064794 has retired it. Thank you for your suggestion!
